name: CaptureTheFart
version: 0.8
author: Bobthe28th
main: me.bobthe28th.capturethefart.Main
description: Capture the flag but funnie
api-version: 1.18
depend: [ProtocolLib]
commands:
  ctfstart:
    description: Starts the CTF match
    usage: /<command>
  ctfjoin:
    description: Joins a player to CTF
    usage: /<command> target
  ctfleave:
    description: Makes a player leave CTF
    usage: /<command> target
  ctffulljoin:
    description: Joins a player to CTF with a class on a team
    usage: /<command> target class team
  ctfteamjoin:
    description: Joins a player to a CTF team
    usage: /<command> target team
  ctfteamleave:
    description: Makes a player leave a CTF team
    usage: /<command> target team
  ctfteams:
    description: Lists the teams and their players
    usage: /<command>
  ctfsetclass:
    description: Sets a player to a class
    usage: /<command> target class
  ctfleaveclass:
    description: Removes a player from a class
    usage: /<command> target
  fly:
    description: toggles flight
    usage: /<command>
  heal:
    description: heals
    usage: /<command>
  test:
    description: for debug
    usage: /<command>
  music:
    description: plays music
    usage: /<command> [play,stop] song
  ctfhelp:
    description: Gets a description of a class
    usage: /<command> class
  ctfsetmap:
    description: Sets the map
    usage: /<command> map
  removeblocks:
    description: Removes all blocks placed by builder
    usage: /<command>